### ISSUE TITLE
Graphql schema.prisma with DateTime format error

### ISSUE THREAD

**Issue by artsfrontend** [Asjas/prisma-redis-middleware#237]
Unable to serialize value '2022-08-29T12:32:34.803Z' as it's not an instance of 'Date'

fields  in schema.prisma
updatedAt    DateTime? @updatedAt
or
createdAt      DateTime   @default(now())

"@prisma/client": "4.2.1",
"prisma-redis-middleware": "^4.1.1",
"graphql": "^15.3.0",
"type-graphql": "^1.1.1",

**Comment by Asjas** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by TheCulturedOne** [comment]
I have the same issue. This seems to be from serializing DateTime values. Here is an example error `{
      "message": "Unable to serialize value '2022-10-11T16:27:32.111Z' as it's not an instance of 'Date'",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "todos",
        0,
        "user",
        "created_at"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unable to serialize value '2022-10-11T16:27:32.111Z' as it's not an instance of 'Date'",
            "    at GraphQLScalarType.serialize (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/type-graphql/dist/scalars/isodate.js:18:19)",
            "    at completeLeafValue (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:653:37)",
            "    at completeValue (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:578:12)",
            "    at resolveField (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:590:12)",
            "    at resolveField (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/Users/mugur/Work/clustered-nodejs-with-redis-and-postgresql/node_modules/graphql/execution/execute.js:292:18)"
          ]
        }
      }
    },`  Here is a public repo where you can reproduce the issue: https://gitlab.com/theculturedone/clustered-nodejs-with-redis-and-postgresql. First query will be ok, from the second one onwards(basically anything comming out of the redis cache will have this error if it has created_at or updated_at included in querries) everything will fail with that error at the graphql layer.

**Comment by TheCulturedOne** [comment]
I have also experimented with setting the todo's object type to a costum graphqlAnyScalar ive made and there doesen't seem to be any changes everything will still fail.

**Comment by luluhoc** [comment]
` LOG  [GraphQL error]: Message: Expected `DateTime.serialize("2022-12-01T11:22:11.000Z")` to return non-nullable value, returned: null, Location: [object Object], Path: me,datedernachat` 

using nest
